### ISSUE TITLE
Inconsistent data type issue on windows

### ISSUE THREAD

**Issue by pratapvardhan** [blaze/blaze#1349]
On windows machine, two test cases, have type check issues.

- blaze/compute/tests/test_pandas_compute.py::test_join_promotion FAILED
- blaze/compute/tests/test_postgresql_compute.py::test_concat FAILED

```python
_____________________________ test_join_promotion _____________________________

    def test_join_promotion():
        a_data = pd.DataFrame([[0.0, 1.5], [1.0, 2.5]], columns=list('ab'))
        b_data = pd.DataFrame([[0, 1], [1, 2]], columns=list('ac'))
        a = symbol('a', discover(a_data))
        b = symbol('b', discover(b_data))
    
        joined = join(a, b, 'a')
>       assert joined.dshape == dshape('var * {a: float64, b: float64, c: int64}')
E       assert dshape("var *...4, c: int64}") == dshape("var * ...4, c: int64}")
E         Full diff:
E         - dshape("var * {a: float64, b: ?float64, c: int64}")
E         ?                               -
E         + dshape("var * {a: float64, b: float64, c: int64}")

blaze\compute\tests\test_pandas_compute.py:324: AssertionError
_________________________________ test_concat _________________________________

sql_two_tables = (Table('tbl4', MetaData(bind=Engine(postgresql://postgres@localhost/test)), Column('a', Integer(), table=<tbl4>, nulla...bind=Engine(postgresql://postgres@localhost/test)), Column('a', Integer(), table=<tbl3>, nullable=False), schema=None))

    def test_concat(sql_two_tables):
        t_table, u_table = sql_two_tables
        t_data = pd.DataFrame(np.arange(5), columns=['a'])
        u_data = pd.DataFrame(np.arange(5, 10), columns=['a'])
        odo(t_data, t_table)
        odo(u_data, u_table)
    
        t = symbol('t', discover(t_data))
        u = symbol('u', discover(u_data))
        tm.assert_frame_equal(
            odo(
                compute(concat(t, u).sort('a'), {t: t_table, u: u_table}),
                pd.DataFrame,
            ),
>           pd.DataFrame(np.arange(10), columns=['a']),
        )
~
~
~
~
    {1}
    [left]:  {2}
    [right]: {3}""".format(obj, message, left, right)
>       raise AssertionError(msg)
E       AssertionError: Attributes are different
E       
E       Attribute "dtype" are different
E       [left]:  int64
E       [right]: int32
```

I suspect both are occuring due a pandas issue on types?

**Comment by pratapvardhan** [comment]
I upgraded from pandas `0.17.0` to `0.17.1` thinking, tests still fail on windows.

And, raising it as windows speicifc issues, since travilsci builds on linux seems to passing all tests.

**Comment by cowlicks** [comment]
Hello @pratapvardhan the `test_join_promotion` bug comes up because the latest blaze depends on the latest version of odo. What version of odo are you on?

We will be releasing new odo, and anaconda packages soon which should fix this.

**Comment by pratapvardhan** [comment]
Ah, thanks @cowlicks 

I'm on
```python
In [20]: odo.__version__
Out[20]: u'0.3.4'
```

which I think, is the latest stable release?

**Comment by llllllllll** [comment]
The `test_concat` failure looks like you are using 32bit and the default dtype for arange is int32 instead of int64. Which version of blaze are you on, the last stable release should work with with the version of odo you specified. If you are on on master of blaze for development, you will need to also use master of odo, and probably datashape.

**Comment by pratapvardhan** [comment]
@llllllllll -- Systems specs are like

1. Python 2.7.10 |Anaconda 2.4.0 (64-bit)| (default, Dec  1 2015, 11:29:38) [MSC v.1500 64 bit (AMD64)]
2. Blaze on master
3. odo on '0.3.4'
4. datashape on '0.4.7+87.g114cef5'

I'll check with odo master.

**Comment by cowlicks** [comment]
@pratapvardhan update? This should be fixed with newest release of the datashape + odo + blaze stack.

**Comment by pratapvardhan** [comment]
@cowlicks -- Sorry, it's been a while. Just checked with odo 0.4.0 `test_join_promotion` is passing. But, `test_concat` is still failing.

**Comment by pratapvardhan** [comment]
Just checked with following versions

```
In [4]: blaze.__version__
Out[4]: '0.10.0rc4+0.g6961844.dirty'

In [5]: datashape.__version__
Out[5]: u'0.5.0'

In [6]: odo.__version__
Out[6]: u'0.4.0'
```

`blaze/compute/tests/test_postgresql_compute.py::test_concat` is still failing.
